// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <amrexPluginInfo.h>

VISIT_DATABASE_PLUGIN_ENTRY(amrex,Engine)

// ****************************************************************************
//  Method: amrexEnginePluginInfo::GetWriter
//
//  Purpose:
//      Sets up a amrex writer.
//
//  Returns:    A amrex writer.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabaseWriter *
amrexEnginePluginInfo::GetWriter(void)
{
    return NULL;
}
