// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <amrexPluginInfo.h>
#include <avtamrexFileFormat.h>
#include <avtMTMDFileFormatInterface.h>
#include <avtGenericDatabase.h>

// ****************************************************************************
//  Method:  amrexCommonPluginInfo::GetDatabaseType
//
//  Purpose:
//    Returns the type of a amrex database.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
DatabaseType
amrexCommonPluginInfo::GetDatabaseType()
{
    return DB_TYPE_MTMD;
}

// ****************************************************************************
//  Method: amrexCommonPluginInfo::SetupDatabase
//
//  Purpose:
//      Sets up a amrex database.
//
//  Arguments:
//      list    A list of file names.
//      nList   The number of timesteps in list.
//      nBlocks The number of blocks in the list.
//
//  Returns:    A amrex database from list.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabase *
amrexCommonPluginInfo::SetupDatabase(const char *const *list,
                                   int nList, int nBlock)
{
    if (nBlock <= 0)
    {
        nBlock = 1;
    }
    int nTimestepGroups = nList / nBlock;
    if (nTimestepGroups <= 0)
    {
        nTimestepGroups = 1;
    }

    avtMTMDFileFormat **ffl = new avtMTMDFileFormat *[nTimestepGroups];
    for (int i = 0; i < nTimestepGroups; i++)
    {
        const int index = i * nBlock;
        ffl[i] = new avtamrexFileFormat(list[index]);
    }
    avtMTMDFileFormatInterface *inter
           = new avtMTMDFileFormatInterface(ffl, nTimestepGroups);
    return new avtGenericDatabase(inter);
}
