// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

// ****************************************************************************
//  File: amrexPluginInfo.C
// ****************************************************************************

#include <amrexPluginInfo.h>

#include <visit-config.h>
VISIT_PLUGIN_VERSION(amrex,DBP_EXPORT)

VISIT_DATABASE_PLUGIN_ENTRY(amrex,General)

// ****************************************************************************
//  Method: amrexGeneralPluginInfo::GetName
//
//  Purpose:
//    Return the name of the database plugin.
//
//  Returns:    A pointer to the name of the database plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
amrexGeneralPluginInfo::GetName() const
{
    return "amrex-plotfile";
}

// ****************************************************************************
//  Method: amrexGeneralPluginInfo::GetVersion
//
//  Purpose:
//    Return the version of the database plugin.
//
//  Returns:    A pointer to the version of the database plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
amrexGeneralPluginInfo::GetVersion() const
{
    return "";
}

// ****************************************************************************
//  Method: amrexGeneralPluginInfo::GetID
//
//  Purpose:
//    Return the id of the database plugin.
//
//  Returns:    A pointer to the id of the database plugin.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

const char *
amrexGeneralPluginInfo::GetID() const
{
    return "amrex_";
}
// ****************************************************************************
//  Method: amrexGeneralPluginInfo::EnabledByDefault
//
//  Purpose:
//    Return true if this plugin should be enabled by default; false otherwise.
//
//  Returns:    true/false
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

bool
amrexGeneralPluginInfo::EnabledByDefault() const
{
    return true;
}
// ****************************************************************************
//  Method: amrexGeneralPluginInfo::HasWriter
//
//  Purpose:
//    Return true if this plugin has a database writer.
//
//  Returns:    true/false
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************

bool
amrexGeneralPluginInfo::HasWriter() const
{
    return false;
}
// ****************************************************************************
//  Method:  amrexGeneralPluginInfo::GetDefaultFilePatterns
//
//  Purpose:
//    Returns the default patterns for a amrex database.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
std::vector<std::string>
amrexGeneralPluginInfo::GetDefaultFilePatterns() const
{
    std::vector<std::string> defaultPatterns;
    defaultPatterns.push_back("*.amrex");

    return defaultPatterns;
}

// ****************************************************************************
//  Method:  amrexGeneralPluginInfo::AreDefaultFilePatternsStrict
//
//  Purpose:
//    Returns if the file patterns for a amrex database are
//    intended to be interpreted strictly by default.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
bool
amrexGeneralPluginInfo::AreDefaultFilePatternsStrict() const
{
    return false;
}

// ****************************************************************************
//  Method:  amrexGeneralPluginInfo::OpensWholeDirectory
//
//  Purpose:
//    Returns if the amrex plugin opens a whole directory name
//    instead of a single file.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
bool
amrexGeneralPluginInfo::OpensWholeDirectory() const
{
    return false;
}
