OpenDatabase("/Users/benwibking/amrex-visit-plugin/example_data/bp5_2d.amrex")
AddPlot("Pseudocolor", "gasDensity")
DrawPlots()
Query("NumZones")
print("NumZones before InverseGhost", GetQueryOutputValue())
AddOperator("InverseGhostZone")
DrawPlots()
Query("NumZones")
print("NumZones after InverseGhost", GetQueryOutputValue())
DeleteAllPlots()
